data:
    modality: "1D"
    dataset: "MixedPolynomial"
    num_data: 4000
    dimension: 100
    hyp_len: 0.8
    hyp_gain: 1.0
    num_workers: 4

model:
    model_type: "FNO"
    n_modes: [100,]
    hidden_channels: 256
    in_channels: 5  # 1(signal) + 4(condition)
    out_channels: 1
    lifting_channels: 256
    projection_channels: 256
    n_layers: 4
    norm: 'group_norm'
    preactivation: True
    skip: 'soft-gating'
    separable: True
    factorization: null
    rank: 1
    joint_factorization: True
    fixed_rank_modes: False
    implementation: 'factorized'
    is_conditional: True  # 조건부 생성 플래그
    ckpt_dir: "./outs/mixed_polynomial_1d_exp/logs/ckpt.pth"

diffusion:
    beta_schedule: "cosine"
    num_diffusion_timesteps: 1000

training:
    batch_size: 100
    n_epochs: 2000
    ckpt_store: 100

sampling:
    batch_size: 1000
    clamp_threshold: 1000
    target_degree: 4  # 샘플링 시 기본값 (2, 4, 6, 8 중 하나)

optim:
    lr: 0.00001
    grad_clip: 1.0 